import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.112.4';
import { checkAnswer, generateQuestion, GENERATOR_VERSION } from './generators.ts';
import { skills, courses } from './curriculum.ts';
import type { Question } from './types.ts';

const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS', 'Content-Type': 'application/json' };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: cors });
const fail = (message: string, status = 400) => json({ error: message }, status);
const url = Deno.env.get('SUPABASE_URL')!; const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin = createClient(url, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } });
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const answerText = (x: string | string[]) => Array.isArray(x) ? JSON.stringify(x.slice(0, 30)) : x.slice(0, 500);
const isPlainObject = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
function publicQuestion(question: Question, id: string) { const { correctAnswer: _answer, explanationSteps: _steps, hints: _hints, generatorSeed: _seed, generatorVersion: _version, ...safe } = question; return { ...safe, id, hasHints: true }; }
async function authenticate(request: Request): Promise<{ userId: string } | { error: Response }> { const header = request.headers.get('authorization') ?? ''; if (!header.toLowerCase().startsWith('bearer ')) return { error: fail('Sign-in required.', 401) }; const { data, error } = await admin.auth.getUser(header.slice(7).trim()); return error || !data.user ? { error: fail('Your session expired. Please sign in again.', 401) } : { userId: data.user.id }; }
async function ensureProfile(userId: string) { const { error } = await admin.from('mq_profiles').upsert({ user_id: userId }, { onConflict: 'user_id', ignoreDuplicates: true }); if (error) throw new Error('Could not access your profile.'); }

Deno.serve(async request => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: cors }); if (request.method !== 'POST') return fail('POST required.', 405);
  if (Number(request.headers.get('content-length') ?? 0) > 20000) return fail('Request is too large.', 413);
  let body: Record<string, unknown>; try { const raw = await request.text(); if (raw.length > 20000) return fail('Request is too large.', 413); const parsed: unknown = JSON.parse(raw); if (!isPlainObject(parsed)) return fail('Send a JSON object.'); body = parsed; } catch { return fail('Send a JSON object.'); }
  const action = typeof body.action === 'string' ? body.action : ''; const auth = await authenticate(request); if ('error' in auth) return auth.error; const userId = auth.userId;
  try { await ensureProfile(userId);
    if (action === 'me') { const [p, total, progress, cosmetics] = await Promise.all([admin.from('mq_profiles').select('xp,coins,streak,course_id').eq('user_id', userId).single(), admin.from('mq_attempts').select('id,correct', { count: 'exact', head: false }).eq('user_id', userId), admin.from('mq_progress').select('skill_id,attempts,correct,rating,interval_days,due_at').eq('user_id', userId), admin.from('mq_cosmetics').select('cosmetic_id').eq('user_id', userId)]); if (p.error || total.error || progress.error || cosmetics.error) return fail('Could not load cloud progress.', 503); return json({ profile: { xp: p.data.xp, coins: p.data.coins, streak: p.data.streak, courseId: p.data.course_id }, totals: { attempts: total.count ?? 0, corrects: (total.data ?? []).filter(x => x.correct).length }, progress: (progress.data ?? []).map(x => ({ skillId: x.skill_id, attempts: x.attempts, correct: x.correct, rating: Number(x.rating), intervalDays: Number(x.interval_days), dueAt: x.due_at })), owned: (cosmetics.data ?? []).map(x => x.cosmetic_id) }); }
    if (action === 'issue') { const skillId = typeof body.skillId === 'string' ? body.skillId : ''; if (!skills.some(s => s.id === skillId)) return fail('Unknown skill.', 400); const budget = await admin.rpc('mq_reserve_issue', { p_user_id: userId }); if (budget.error || !budget.data) return fail(budget.error ? 'Could not reserve practice capacity. Please retry.' : 'Practice limit reached for the day. Please return tomorrow.', budget.error ? 503 : 429); const { data: learned, error: learnedError } = await admin.from('mq_progress').select('rating').eq('user_id', userId).eq('skill_id', skillId).maybeSingle(); if (learnedError) return fail('Could not prepare your adaptive difficulty.', 503); const difficulty = Math.max(1, Math.min(10, Math.round(3 + Number(learned?.rating ?? 0)))); const seed = crypto.getRandomValues(new Uint32Array(1))[0] % 2147483647; const question = generateQuestion(skillId, difficulty, seed); const { data, error } = await admin.from('mq_questions').insert({ user_id: userId, skill_id: skillId, difficulty: question.difficulty, prompt: question.prompt, type: question.type, choices: question.choices ?? null, expected_answer: JSON.stringify(question.correctAnswer), solution: question.explanationSteps, hints: question.hints, generator_seed: question.generatorSeed, generator_version: GENERATOR_VERSION }).select('id').single(); if (error || !data) return fail('Could not prepare a practice question.', 500); return json({ question: publicQuestion(question, data.id) }); }
    if (action === 'hint') { const questionId = typeof body.questionId === 'string' ? body.questionId : ''; const tier = body.tier; if (!UUID.test(questionId) || !Number.isInteger(tier)) return fail('Invalid hint request.'); const { data, error } = await admin.rpc('mq_record_hint', { p_user_id: userId, p_question_id: questionId, p_tier: tier }); if (error) return fail('That hint is no longer available.', 409); return json(data); }
    if (action === 'answer') { const questionId = typeof body.questionId === 'string' ? body.questionId : ''; const incoming = body.answer; const seconds = body.seconds; if (!UUID.test(questionId) || !(typeof incoming === 'string' || Array.isArray(incoming)) || (typeof incoming === 'string' && incoming.length > 500) || (Array.isArray(incoming) && (incoming.length > 20 || incoming.some(x => typeof x !== 'string' || x.length > 120))) || !Number.isInteger(seconds) || seconds < 0 || seconds > 7200) return fail('Invalid answer.'); const { data: row, error: readError } = await admin.from('mq_questions').select('id,skill_id,difficulty,prompt,type,choices,expected_answer,solution,hint_count,generator_seed,generator_version,expires_at').eq('id', questionId).eq('user_id', userId).maybeSingle(); if (readError) return fail('Could not verify this question.', 503); if (!row || new Date(row.expires_at).getTime() < Date.now()) return fail('This question expired. Start a new trail.', 409); const question: Question = { id: row.id, skillId: row.skill_id, difficulty: row.difficulty, prompt: row.prompt, type: row.type, choices: row.choices ?? undefined, correctAnswer: JSON.parse(row.expected_answer), explanationSteps: row.solution, hints: [], generatorSeed: row.generator_seed, generatorVersion: row.generator_version }; const correct = checkAnswer(question, incoming as string | string[]); const { data: graded, error: gradeError } = await admin.rpc('mq_record_attempt', { p_user_id: userId, p_question_id: questionId, p_answer: answerText(incoming as string | string[]), p_correct: correct, p_seconds: seconds }); if (gradeError) return fail(gradeError.message.includes('expired') ? 'This question expired. Start a new trail.' : 'Could not record that answer.', 409); return json({ correct: Boolean(graded.correct), alreadyGraded: Boolean(graded.already_graded), xpAwarded: Number(graded.xp_awarded ?? 0), coinsAwarded: Number(graded.coins_awarded ?? 0), streak: Number(graded.streak ?? 0), explanationSteps: row.solution }); }
    if (action === 'course') { const courseId = typeof body.courseId === 'string' ? body.courseId : ''; if (!courses.some(c => c.id === courseId)) return fail('Unknown course.'); const { error } = await admin.from('mq_profiles').update({ course_id: courseId, updated_at: new Date().toISOString() }).eq('user_id', userId); if (error) return fail('Could not save course choice.', 503); return json({ courseId }); }
    if (action === 'export') { const max = 1000; const [p, progress, attempts, cosmetics] = await Promise.all([admin.from('mq_profiles').select('user_id,display_name,xp,coins,streak,course_id,created_at,updated_at').eq('user_id', userId).maybeSingle(), admin.from('mq_progress').select('skill_id,attempts,correct,rating,interval_days,due_at,updated_at').eq('user_id', userId).limit(max), admin.from('mq_attempts').select('id,question_id,skill_id,answer,correct,hint_count,seconds,xp_awarded,coins_awarded,created_at').eq('user_id', userId).order('created_at', { ascending: false }).limit(max), admin.from('mq_cosmetics').select('cosmetic_id,purchased_at').eq('user_id', userId).limit(max)]); if (p.error || progress.error || attempts.error || cosmetics.error) return fail('Export unavailable.', 503); return json({ profile: p.data, progress: progress.data ?? [], attempts: attempts.data ?? [], cosmetics: cosmetics.data ?? [], exportLimit: max }); }
    if (action === 'purchase') { const cosmeticId = typeof body.cosmeticId === 'string' ? body.cosmeticId : ''; if (!['mosswing-green', 'aether-crown', 'crystal-boots', 'guardian-pin'].includes(cosmeticId)) return fail('Unknown cosmetic.'); const { data, error } = await admin.rpc('mq_purchase_cosmetic', { p_user_id: userId, p_cosmetic_id: cosmeticId }); if (error) return fail(error.message.includes('not enough') ? 'Not enough shards.' : 'Could not collect that badge.', 409); return json(data); }
    if (action === 'delete-account') { if (body.confirmation !== 'DELETE') return fail('Type DELETE to confirm account deletion.'); const { error } = await admin.auth.admin.deleteUser(userId); return error ? fail('Account deletion failed; no app data was changed.', 500) : json({ deleted: true }); }
    if (action === 'tutor') return fail('Tutor is not enabled in this beta build; use the three deterministic hints.', 503); return fail('Unknown action.');
  } catch (error) { console.error('mathquest-api', error); return fail('The Aether relay encountered an error. Please retry.', 500); }
});
