-- MathQuest additive schema. It does not alter or drop unrelated application tables.
create extension if not exists pgcrypto;
create table if not exists public.mq_profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Aether explorer', xp integer not null default 0 check (xp >= 0), coins integer not null default 0 check (coins >= 0), streak integer not null default 0 check (streak >= 0), course_id text not null default 'ga-algebra', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.mq_questions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, skill_id text not null, difficulty smallint not null check (difficulty between 1 and 10), prompt text not null check (char_length(prompt) <= 1200), type text not null check (type in ('numeric','multiple-choice','multi-select')), choices jsonb, expected_answer text not null, solution jsonb not null, hints jsonb not null, generator_seed integer not null, generator_version integer not null, hint_count smallint not null default 0 check (hint_count between 0 and 3), expires_at timestamptz not null default (now() + interval '2 hours'), created_at timestamptz not null default now());
create index if not exists mq_questions_user_created on public.mq_questions(user_id, created_at desc);
create table if not exists public.mq_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, question_id uuid not null references public.mq_questions(id) on delete cascade, skill_id text not null, answer text not null check (char_length(answer) <= 500), correct boolean not null, hint_count smallint not null check (hint_count between 0 and 3), seconds integer not null check (seconds between 0 and 7200), xp_awarded integer not null default 0 check (xp_awarded >= 0), coins_awarded integer not null default 0 check (coins_awarded >= 0), created_at timestamptz not null default now(), unique(user_id, question_id));
create index if not exists mq_attempts_user_created on public.mq_attempts(user_id, created_at desc);
create table if not exists public.mq_progress (user_id uuid not null references auth.users(id) on delete cascade, skill_id text not null, attempts integer not null default 0 check (attempts >= 0), correct integer not null default 0 check (correct >= 0), rating numeric(7,3) not null default 0, interval_days numeric(7,2) not null default 0, due_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(user_id, skill_id));
create table if not exists public.mq_cosmetics (user_id uuid not null references auth.users(id) on delete cascade, cosmetic_id text not null check (cosmetic_id in ('mosswing-green','aether-crown','crystal-boots','guardian-pin')), purchased_at timestamptz not null default now(), primary key(user_id, cosmetic_id));
create table if not exists public.mq_issue_budgets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, reserved_at timestamptz not null default now()); create index if not exists mq_issue_budgets_user_time on public.mq_issue_budgets(user_id,reserved_at desc);
alter table public.mq_profiles enable row level security; alter table public.mq_questions enable row level security; alter table public.mq_attempts enable row level security; alter table public.mq_progress enable row level security; alter table public.mq_cosmetics enable row level security; alter table public.mq_issue_budgets enable row level security;
drop policy if exists mq_profiles_select_own on public.mq_profiles; create policy mq_profiles_select_own on public.mq_profiles for select using (user_id = auth.uid());
drop policy if exists mq_attempts_select_own on public.mq_attempts; create policy mq_attempts_select_own on public.mq_attempts for select using (user_id = auth.uid());
drop policy if exists mq_progress_select_own on public.mq_progress; create policy mq_progress_select_own on public.mq_progress for select using (user_id = auth.uid());
drop policy if exists mq_cosmetics_select_own on public.mq_cosmetics; create policy mq_cosmetics_select_own on public.mq_cosmetics for select using (user_id = auth.uid());
-- mq_questions has no client policy: expected answers and replay data are service-only.
create or replace function public.mq_reserve_issue(p_user_id uuid) returns boolean language plpgsql security definer set search_path = pg_catalog, public as $$
declare issued integer; begin if p_user_id is null then raise exception 'invalid user'; end if; perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 901)); select count(*) into issued from public.mq_issue_budgets where user_id=p_user_id and reserved_at >= now()-interval '24 hours'; if issued >= 60 then return false; end if; insert into public.mq_issue_budgets(user_id) values(p_user_id); return true; end; $$;
create or replace function public.mq_record_hint(p_user_id uuid, p_question_id uuid, p_tier integer) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare q public.mq_questions%rowtype; chosen text; begin if p_user_id is null or p_question_id is null or p_tier not between 1 and 3 then raise exception 'invalid hint request'; end if; select * into q from public.mq_questions where id=p_question_id and user_id=p_user_id and expires_at>now() for update; if not found then raise exception 'question unavailable'; end if; if exists(select 1 from public.mq_attempts where user_id=p_user_id and question_id=p_question_id) then raise exception 'question already graded'; end if; if p_tier <> q.hint_count+1 then raise exception 'hints must be revealed in order'; end if; chosen:=q.hints->>(p_tier-1); update public.mq_questions set hint_count=p_tier where id=p_question_id; return jsonb_build_object('hint',chosen,'tier',p_tier); end; $$;
create or replace function public.mq_record_attempt(p_user_id uuid, p_question_id uuid, p_answer text, p_correct boolean, p_seconds integer) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare q public.mq_questions%rowtype; old public.mq_attempts%rowtype; award_xp integer; award_coins integer; next_streak integer; begin if p_user_id is null or p_question_id is null or char_length(coalesce(p_answer,''))>500 or p_seconds not between 0 and 7200 then raise exception 'invalid attempt'; end if; select * into q from public.mq_questions where id=p_question_id and user_id=p_user_id and expires_at>now() for update; if not found then raise exception 'question unavailable or expired'; end if; select * into old from public.mq_attempts where user_id=p_user_id and question_id=p_question_id; if found then return jsonb_build_object('correct',old.correct,'already_graded',true,'xp_awarded',0,'coins_awarded',0,'streak',(select streak from public.mq_profiles where user_id=p_user_id)); end if; award_xp:=case when p_correct then greatest(5,15-q.hint_count*3) else 1 end; award_coins:=case when p_correct then greatest(1,3-q.hint_count) else 0 end; insert into public.mq_profiles(user_id) values(p_user_id) on conflict(user_id) do nothing; update public.mq_profiles set xp=xp+award_xp,coins=coins+award_coins,streak=case when p_correct then streak+1 else 0 end,updated_at=now() where user_id=p_user_id returning streak into next_streak; insert into public.mq_attempts(user_id,question_id,skill_id,answer,correct,hint_count,seconds,xp_awarded,coins_awarded) values(p_user_id,p_question_id,q.skill_id,left(p_answer,500),p_correct,q.hint_count,p_seconds,award_xp,award_coins); insert into public.mq_progress(user_id,skill_id,attempts,correct,rating,interval_days,due_at) values(p_user_id,q.skill_id,1,case when p_correct then 1 else 0 end,case when p_correct then 1 else 0 end,case when p_correct then 2 else .25 end,now()+case when p_correct then interval '2 days' else interval '1 day' end) on conflict(user_id,skill_id) do update set attempts=mq_progress.attempts+1,correct=mq_progress.correct+case when p_correct then 1 else 0 end,rating=greatest(0,mq_progress.rating+case when p_correct then .2 else -.1 end),interval_days=case when p_correct then least(90,mq_progress.interval_days*1.8+1) else 1 end,due_at=now()+case when p_correct then make_interval(days=>least(90,ceil(mq_progress.interval_days*1.8+1)::integer)) else interval '1 day' end,updated_at=now(); return jsonb_build_object('correct',p_correct,'already_graded',false,'xp_awarded',award_xp,'coins_awarded',award_coins,'streak',next_streak); end; $$;
create or replace function public.mq_purchase_cosmetic(p_user_id uuid,p_cosmetic_id text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare p public.mq_profiles%rowtype; cost integer; already boolean; owned jsonb; begin cost:=case p_cosmetic_id when 'mosswing-green' then 0 when 'aether-crown' then 35 when 'crystal-boots' then 55 when 'guardian-pin' then 80 else -1 end; if p_user_id is null or cost<0 then raise exception 'unknown cosmetic'; end if; select * into p from public.mq_profiles where user_id=p_user_id for update; if not found then raise exception 'profile unavailable'; end if; select exists(select 1 from public.mq_cosmetics where user_id=p_user_id and cosmetic_id=p_cosmetic_id) into already; if not already and p.coins<cost then raise exception 'not enough shards'; end if; if not already then update public.mq_profiles set coins=coins-cost,updated_at=now() where user_id=p_user_id; insert into public.mq_cosmetics(user_id,cosmetic_id) values(p_user_id,p_cosmetic_id); end if; select coalesce(jsonb_agg(cosmetic_id order by cosmetic_id),'[]'::jsonb) into owned from public.mq_cosmetics where user_id=p_user_id; return jsonb_build_object('coins',(select coins from public.mq_profiles where user_id=p_user_id),'owned',owned); end; $$;
revoke all on function public.mq_reserve_issue(uuid) from public,anon,authenticated; revoke all on function public.mq_record_hint(uuid,uuid,integer) from public,anon,authenticated; revoke all on function public.mq_record_attempt(uuid,uuid,text,boolean,integer) from public,anon,authenticated; revoke all on function public.mq_purchase_cosmetic(uuid,text) from public,anon,authenticated;
grant execute on function public.mq_reserve_issue(uuid) to service_role; grant execute on function public.mq_record_hint(uuid,uuid,integer) to service_role; grant execute on function public.mq_record_attempt(uuid,uuid,text,boolean,integer) to service_role; grant execute on function public.mq_purchase_cosmetic(uuid,text) to service_role;
